---
- include: includes/obtain_session_token.yaml
- hosts: localhost
  vars_prompt:
    - name: env_prefix
      private: false
    - name: mfa_required
      default: true
      private: false
  tasks:
    - name: "Ansible User"
      iam:
        iam_type: user
        name: "{{ env_prefix }}-ansible-admin"
        access_key_state: create
        state: present
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
      register: ansible_user_info
      no_log: True
    - name: "delegate-admin-details/{{ env_prefix }} dir"
      file:
        state: directory
        path: "{{ playbook_dir }}/delegate-admin-details/{{ env_prefix }}"
    - name: "Check if AWS Creds Changed"
      set_fact:
        aws_creds_changed: "{{ ansible_user_info.changed and ansible_user_info.user_meta is defined }}"
    - name: "vault.yaml"
      template:
        src: templates/vault.yaml.j2
        dest: "{{ playbook_dir }}/delegate-admin-details/{{ env_prefix }}/aws_creds_vault.yaml"
        mode: 0600
      when: aws_creds_changed
    - name: "Load Existing Vars"
      include_vars:
        file: "{{ playbook_dir }}/delegate-admin-details/{{ env_prefix }}/aws_creds_vars.yaml"
        name: aws_creds_vars
    - name: "Set User ARN"
      set_fact:
        aws_creds_user_arn: "{{ ansible_user_info.user_meta.created_user.arn if aws_creds_changed else aws_creds_vars.aws_user_arn }}"
    - name: "vars.yaml"
      template:
        src: templates/vars.yaml.j2
        dest: "{{ playbook_dir }}/delegate-admin-details/{{ env_prefix }}/aws_creds_vars.yaml"
    - name: "User Policies"
      iam_policy:
        iam_type: user
        iam_name: "{{ env_prefix }}-ansible-admin"
        policy_name: "{{ item.key }}"
        policy_json: "{{ lookup('template', 'templates/iam_policy/' + item.key + '.json.j2') }}"
        state: "{{ item.value }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
      with_dict:
        require_https: present
        require_mfa: "{{ 'present' if mfa_required|bool else 'absent' }}"
        scoped_access: present
      loop_control:
        label: "{{ item.key }}"

    - debug:
        msg: |
          {{ env_prefix }}-ansible-admin user created in AWS account, this user must use MFA to get a temporary STS token.
          When authenticated with a MFA token this user has limited admin rights to the account.
          
          You must assign an MFA device to the {{ env_prefix }}-ansible-admin user in the AWS console.
          Ensure the ARN is correct in
          {{ playbook_dir }}/delegate-admin-details/{{ env_prefix }}/aws_creds_vars.yaml
          
          API Access Keys for this user are in:
          {{ playbook_dir }}/delegate-admin-details/{{ env_prefix }}/aws_creds_vault.yaml
          
          You really should encrypt this file with ansible-vault.
