# The prefix indicating the logical environment created users can modify. The created
# users are limited to modifying resources that start with this prefix followed by -
env_prefix: dev

# The regions that created users are allowed to interact with. For any region scoped
# resources the created users can only access resources in these regions
aws_allowed_regions:
  - ap-southeast-1
  - ap-southeast-2
  - ap-southeast-3

# The region to connect to to work with IAM
aws_connect_region: us-west-1

# The id of the AWS account, this is used to build ARNs
aws_account: ACCOUNT_ID

# The ARN of the MFA token of the admin user that's used to create other users
mfa_token_arn: arn:aws:iam::{{ aws_account }}:mfa/USER_NAME

# The vault file containing the static aws access keys used to obtain a STS
# token using Multi-Factor Authentication
static_aws_key_vault: "{{ playbook_dir }}/vaults/aws_creds.yaml"

# Connection detail setup since all AWS modification actually happens on localhost
ansible_connection: local
ansible_python_interpreter: python
